agrupem/routes/web.php
<?php

use App\Http\Controllers\ContactFormController;
use App\Http\Controllers\TextController;

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('lang/{locale}', 'HomeController@lang')->name('language');

Route::get('/home', 'HomeController@index')->name('home'); 

Route::resource('post', 'PostController');
Route::get('/post/create', 'PostController@create')->name('post.create')->middleware('auth');
Route::get('/post/{post}/edit', 'PostController@edit')->name('post.edit')->middleware('auth');
Route::DELETE('/post/{post}', 'PostController@destroy')->name('post.destroy')->middleware('auth');

Route::resource('resource', 'ResourceController')->except('show');
Route::get('/resource/create', 'ResourceController@create')->name('resource.create')->middleware('auth');
Route::get('/resource/{resource}/edit', 'ResourceController@edit')->name('resource.edit')->middleware('auth');
Route::DELETE('/resource/{resource}', 'ResourceController@destroy')->name('resource.destroy')->middleware('auth');

Route::get('/calendar', 'CalendarController@calendar');

Route::resource('event', 'EventController');
Route::get('/event/create', 'EventController@create')->name('event.create')->middleware('auth');
Route::post('/event/deleteImage/{event}', 'EventController@deleteImage')->name('event.imageDelete')->middleware('auth');
Route::get('/event/{event}/edit', 'EventController@edit')->name('event.edit')->middleware('auth');
Route::DELETE('/event/{event}', 'EventController@destroy')->name('event.destroy')->middleware('auth');

Route::get('contact', 'ContactFormController@create');
Route::post('contact', 'ContactFormController@store');

Route::get('quiSom', 'TextController@quiSom')->name('quiSom'); 
Route::get('queFem', 'TextController@queFem')->name('queFem');
Route::get('festeSoci','TextController@festeSoci')->name('festeSoci'); 
Route::get('/colabora','TextController@Colabora')->name('Colabora');

Route::PATCH('text/{text}', 'TextController@update')->name('name.text')->middleware('auth');

agrupem/app/Event.php
<?php

namespace App;

use App;
use App\traits\Multilanguage;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;


class Event extends Model
{
    use Multilanguage;
    protected $fillable=[
        'title_catalan','title_spanish','content_catalan','content_spanish','startDate', 'endDate', 'expired'
    ];
    static function sortByDate()
    {
        $events = Event::all();
        $eventsSortered = $events->sortBy('startDate');
        return $eventsSortered;
    }
    static function getNonExpiredEvents()
    {
        $events = Event::sortByDate()->where('expired',false);
        return $events;
    }
    public function expireEvent()
    {
        $this->expired = true;
        $this->save();
    }
    static function getPastEvents()
    {
        $today = date('Y-m-d');
        $events = Event::all()->where('endDate','<',$today)->where('expired', false);
        return $events;
    }
    static function expirePastEvents()
    {
        $events = Event::getPastEvents();
        foreach ($events as $event) 
        $event->expireEvent();
    }

    private function validateImg($request)
    {
        $request->validate([
                               
            'image' => 'required|image|mimes:jpeg,png,jpg,gif|max:2048'

        ]); 
    } 

    public function uploadImage($request, $event) 
    {
           
        $event->validateImg($request);   
        
        if ($request->hasFile('image')) 
        {
            $image = $request->file('image');
            $filePath = $event->id. '.jpg';
            $image->storeAs("public/events/",$filePath);            
        }
        
    }
    public function imageUrl()
    {
        $route = "storage/public/events/$this->id.jpg";
        if (File::exists($route))
        {
            return $route;
        }
        return false;
    }
}

agrupem/app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class EventController extends Controller
{

    public function index()
    {
        $events=Event::getNonExpiredEvents();
        $calendar = Event::getLocalCalendar();
        return view('event.index',['events'=>$events, 'calendar'=>$calendar]);
    }

    public function create()
    {
        return view('event.create');
    }

    public function store(Request $request)
    {
        $event=Event::create($request->all());
        $event->uploadImage($request,$event);
        return redirect('event');
    }
    
    public function show(Event $event)
    {
        $route = $event->imageUrl($event);
        return view('event.event',['event'=>$event, 'route'=>$route]);
        
    }
    
    public function edit(Event $event)
    {
        return view('event.edit',['event'=>$event]);
    }
    
    public function update(Request $request, Event $event)
    {
        $event->update($request->all());
        $event->uploadImage($request,$event);
        return redirect("event/$event->id");
    }

    public function destroy(Event $event)
    {
        $event->delete();
        return redirect('event');
    }

    public function deleteImage(Event $event)
    {
        Storage::delete("public/events/$event->id.jpg");
        return redirect("event/$event->id");
    }
}

agrupem/resources/views/event/_events-calendar.blade.php
<section id="home_calendar_container" class="col-md-6 d-flex justify-content-center align-items-center col-sm-12">
    <div>
        @include('event.calendar')
    </div>
</section>
<section class="col-md-6 justify-content-center col-sm-12 mb-5">
    <header id="home_event_title" class="shadow-home p-2 pl-3">
        <h1>@lang('home.events')</h1>
    </header>
    <section id="home_events_container" >
            <div class="next_events_container">
            @foreach ($events as $event)
                {{$event->startDate}}
                <h3> {{$event->getLocalTitle()}}</h3>
                <form action="/event/{{$event->id}}" method="GET">
                    <button class="btn btn-primary" type="submit">@lang('home.eventsmore')</button>
                </form>
                <br>
            @endforeach
            </div>
            @auth
                <form method="GET" action="/event/create" class="m-2">
                    <input type="submit" class="btn btn-success" value="Crear">
                </form>
            @endauth
            <div class="m-2">
                <button class="btn btn-secondary" onclick="window.location.href = '/event';">@lang('home.eventsbtn')</button>
            </div>
    </section>
</section>

agrupem/resources/views/event/calendar.blade.php
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css' />

<header id="calendar_title" class="shadow-home p2 pl-3">
    <h3>@lang('home.calendar')</h3>
</header>
<div id='calendar'></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/locales-all.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>
<script src="{{$calendar}}"></script>
<script>
        $('#calendar').fullCalendar({
            events : [
                @foreach($events as $event)
                {
                    title : '{{ $event->getLocalTitle() }}',
                    start : '{{ $event->startDate }}',
                    end : '{{$event->endDate}}',
                    url : '{{ route('event.show', $event->id) }}'
                },
                @endforeach
            ]
        })
</script>

agrupem/resources/views/event/create.blade.php
@extends('layouts.app')

@section('content') 
<div class="container">
    <div class="d-flex flex-wrap justify-content-center">
        <div class="col-md-12">
        <section class="d-flex">
            <form method="POST" action="/event" enctype="multipart/form-data">
                @csrf
                <div class="d-flex flex-wrap">
                    <section class="flex-column col-10 p-2 m-2 box-shadow white-background">
                        <div class="form-group">
                            <label for="title_cat">@lang('form.titlecat')</label> <br>
                            <input id="title_cat" required type="text" name="title_catalan"><br>
                        </div>
                        <div class="form-group">
                            <label for="content_cat">@lang('form.contentcat')</label>
                            <textarea id="content_cat" class="summernote" required type="textarea" name="content_catalan" cols="30" rows="10"></textarea><br>
                        </div>
                    </section>
                    <section class="flex-column col-10 p-2 m-2 box-shadow">
                    <div class="form-group">
                        <label for="title_spa">@lang('form.titlecas')</label><br>
                        <input id="title_spa" type="text" name="title_spanish"><br>
                    </div>
                    <div>
                        <label for="content_spa">@lang('form.contentcat')</label>
                        <textarea id="content_spa" class="summernote" type="textarea" name="content_spanish" cols="30" rows="10"></textarea><br>
                    </div>
                    </section>
                </div>
                <section class="col-10 p-2 m-2 box-shadow">
                    <div class="form-group">
                        <label for="strtDate">@lang('form.datestart')</label>
                        <input id="strtDate" required type="date" name="startDate" value="<?php echo date("Y-m-d");?>"><br>
                    </div>
                    <div class="form-group">
                        <label for="strtDate">@lang('form.dateend')</label>
                        <input id="edDate" required type="date" name="endDate" value="<?php echo date("Y-m-d");?>"><br>
                    </div>
                </section>
                <input class="btn btn-success m-2" type="submit" value="Crear" >
            </form>
        </section>
        </div>
    </div>
</div>
@endsection

agrupem/resources/views/event/edit.blade.php
@extends('layouts.app')
@section('content')

<section class="container-fluid justify-content-center col-12">
    <div class="d-flex flex-wrap">
        <div class="p-2 col-sm-12 col-md-12">
            <form method="POST" action="/event/{{$event->id}}"  enctype="multipart/form-data">
                @csrf
                @method("PATCH")
                <div class="white-background m-2 box-shadow col-md-12">
                    <label for="title_catalan">@lang('form.titlecat')</label><br>
                    <input id="title_catalan" type="text" name="title_catalan" value="{{$event->title_catalan}}"><br>
                    <label for="content_edit_catalan">@lang('form.contentcat')</label><br>
                    <textarea id="content_edit_catalan" name="content_catalan">{{$event->content_catalan}}</textarea><br>
                </div>
                <div class="white-background m-2 box-shadow col-md-12">
                    <label for="title_spanish">@lang('form.titlecas')</label><br>
                    <input id="title_spanish" type="text" name="title_spanish" value="{{$event->title_spanish}}"><br>
                    <label for="content_edit_spanish">@lang('form.contentcas')</label><br>
                    <textarea id="content_edit_spanish" name="content_spanish">{{$event->content_spanish}}</textarea><br>
                    <label for="">@lang('form.datestart')</label>
                    <input type="date" name="startDate" value="{{$event->startDate}}">
                    <label for="">@lang('form.dateend')</label>
                    <input type="date" name="endDate" value="{{$event->endDate}}"><br>
                </div>
                <input type="submit" class="btn btn-success" value="Guardar">
            </form>
        </div>
    </div>
</section>

@endsection

agrupem/resources/views/event/event.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid d-flex flex-wrap col-12 justify-content-center">
   <article class="box-shadow p-3 mb-5 rounded col-sm-12 col-md-12 col-lg-12">
        <header class="text_container text-center shadow-lg">
            <h1>{{$event->getLocalTitle()}}</h1>
        </header>
        <div class="text_container shadow-lg">
            <p>{!! html_entity_decode($event->getLocalContent()) !!}</p>
        </div>
        @auth
        <div class="row admin_button">
            <form action="/event/{{$event->id}}/edit" method="GET">
                <input type="submit" id="button_edit" class = "btn btn-primary mt-4" value="Editar">
            </form>

            <form action="/event/{{$event->id}}" method="post">
            @csrf
            @method('DELETE')
                <input id="button_delete" type="submit" value="Eliminar" class="btn btn-danger mt-4">
            </form>
        </div>
        @endauth 
    </article>
    <div class="d-flex flex-nowrap justify-content-between col-md-6">
        <form method="get" action="/colabora" class="btn btn-primary btn-lg col-sm-12 col-md-6 col-lg-6 m-1">
            <button class="bg-primary buttons"  type="submit">Colabora</button>
        </form>
        <form method="get" action="/hazteSocio" class="btn btn-primary btn-lg col-sm-12 col-md-6 col-lg-6 m-1">
            <a class="btn btn-primary btn-lg col-sm-12 col-md-6 col-lg-6 m-1" type="button" href= "{{ url('/festeSoci') }}"> Hazte Socio</a>
        </form>
    </div>
</div>
@endsection

agrupem/resources/views/event/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid d-flex flex-wrap col-12 flex-wrap justify-content-center">
    <div class="col-12 d-flex justify-content-center">
        <section class="col-md-6 col-sm-12">
            <div class="mb-5">
                    @include('event.calendar')
            </div>
        </section>
    </div>
    <div class="mt-3 col-12 d-flex flex-wrap justify-content-center">
    @foreach ($events as $event)
    <section class="col-md-4 col-sm-12 m-2 shadow-lg white-background">
        <header>
            Evento: {{$event->getLocalTitle()}} 
        </header>
        Fecha: {{$event->startDate}}
        <form action="/event/{{$event->id}}" method="GET">
            <input class="btn btn-primary" type="submit" value="Mostrar Evento">
        </form>
    </section>
    @endforeach
    </div>
</div>
@endsection